cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/gustavo/helpful/ns-allinone-3.22/ns-3.22/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/home/gustavo/helpful/ns-allinone-3.22/ns-3.22/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140338241036752: cxx test.cc -> test.cc.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYTHON_H=1\', \'../test.cc\', \'-c\', \'-o\', \'test.cc.1.o\']\n'
